[package]
name = "phlite_rips"
version = "0.1.0"
edition = "2021"

[lib]
name = "phlite_rips"
path = "src/lib.rs"

[[bin]]
name = "phlite_rips_cli"
path = "src/main.rs"

[dependencies]
csv = "1.3.0"
ordered-float = "4.2.0"
phlite = { version = "0.1.0", path = "../phlite" }
