# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

def grpph(n_vertices:int,edges:typing.Sequence[tuple[int, int, float]]) -> tuple[list[list[float]], list[list[tuple[float, float]]]]:
    ...

def grpph_with_involution(n_vertices:int,edges:typing.Sequence[tuple[int, int, float]]) -> tuple[list[list[float]], list[list[tuple[float, float]]], list[list[tuple[int, int]]]]:
    r"""
    Does the same as `grpph` but does involution to compute representatives.
    """
    ...

